<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Form\ExporterForm $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exporters edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-export.css', 'BulkExport'));
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Create new exporter'), 1, $translate('Bulk Export')); ?>

<div id="content">
    <h2><?php echo $escape($translate('Create new exporter')); ?></h2>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
