<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Interfaces\Writer $writer
 * @var \Zend\Form\Form $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exporters edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-export.css', 'BulkExport'));
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Configure writer'), 1, $translate('Bulk export')); ?>

<div id="content">
    <h2><?php echo $escape($translate('Configure writer')); ?></h2>
    <h3><?php echo $escape(sprintf($translate('Writer: %s'), $writer->getLabel())); ?></h3>
    <p><?php echo $escape($translate('Fill the default values of the writer.')); ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
