<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExporterRepresentation $exporter
 * @var \BulkExport\Writer\WriterInterface $writer
 * @var \Laminas\Form\Form $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exporters edit');
$this->headLink()->appendStylesheet($assetUrl('css/bulk-export-admin.css', 'BulkExport'));

$form->prepare();

$submit = $form->get('form_submit')->get('submit');
$submit->setAttribute('form', $form->getAttribute('id'));
$form->get('form_submit')->remove('submit');
?>

<?= $this->pageTitle($exporter->label(), 1, $translate('Bulk import')) ?>

<div id="bulk-export">
    <h3><?= $escape(sprintf($translate('Writer: %s'), $writer->getLabel())) ?></h3>
    <p><?= $escape($translate('Fill the default values of the writer.')) ?></p>
    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form) ?>
    <?= $this->form()->closeTag() ?>
</div>

<div id="page-actions">
    <?= $this->formSubmit($submit) ?>
</div>
