<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Writer\WriterInterface $writer
 * @var \Laminas\Form\Form $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exporters edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-export-admin.css', 'BulkExport'));
$form->prepare();
?>

<?= $this->pageTitle($translate('Configure writer'), 1, $translate('Bulk export')) ?>

<div id="content">
    <h2><?= $escape($translate('Configure writer')) ?></h2>
    <h3><?= $escape(sprintf($translate('Writer: %s'), $writer->getLabel())) ?></h3>
    <p><?= $escape($translate('Fill the default values of the writer.')) ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
