<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExporterRepresentation $exporter
 * @var \BulkExport\Form\ExporterDeleteForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exporters delete');
$this->headLink()->appendStylesheet($assetUrl('css/bulk-export-admin.css', 'BulkExport'));

$form->prepare();
?>

<?= $this->pageTitle($translate('Exporter'), 1, $translate('Bulk export')) ?>

<div id="bulk-export">
    <h2><?= $escape(sprintf($translate('Delete exporter (%s)'), $exporter->label())) ?></h2>
    <p><?= $escape($translate('Are you sure you want to delete this exporter ?')) ?></p>
    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form) ?>
    <?= $this->form()->closeTag() ?>
</div>
