<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Form\ExporterDeleteForm $form
 * @var \BulkExport\Api\Representation\ExporterRepresentation $entity
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exporters delete');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-export-admin.css', 'BulkExport'));
$form->prepare();
?>

<?= $this->pageTitle($translate('Delete exporter'), 1, $translate('Bulk export')) ?>

<div id="content">
    <h2><?= $escape(sprintf($translate('Delete exporter (%s)'), $entity->label())) ?></h2>
    <p><?= $escape($translate('Are you sure you want to delete this exporter ?')) ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
