<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Form\ExporterDeleteForm $form
 * @var \BulkExport\Api\Representation\ExporterRepresentation $entity
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exporters bulk-exports edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-export-admin.css', 'BulkExport'));
$form->prepare();
?>

<?= $this->pageTitle($translate('Edit exporter'), 1, $translate('Bulk export')) ?>

<div id="content">
    <h2><?= $escape($translate('Edit exporter')) ?></h2>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
