<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExporterRepresentation $exporter
 * @var string $current
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$nav = [
    'exporter' => $translate('Exporter'),
];
$replace = [];
if ($current !== 'exporter') {
    $replace = [
        '<li class="active">' => '<li>',
        'href="#exporter"' => 'href="' . $this->url('admin/bulk-export/id', ['controller' => 'exporter', 'action' => 'edit', 'id' => $exporter->id()]) . '"',
    ];
}
// Check if a config form is available via the formatter_forms registry.
if ($exporter->getConfigFormClass()) {
    $nav['formatter'] = $translate('Formatter');
    if ($current === 'formatter') {
        $replace['<li><a href="#formatter"'] = '<li class="active"><a href="#formatter"';
    } else {
        $replace['href="#formatter"'] = 'href="' . $this->url('admin/bulk-export/id', ['controller' => 'exporter', 'action' => 'configure-formatter', 'id' => $exporter->id()]) . '"';
    }
}
?>

<?= strtr($this->sectionNav($nav), $replace) ?>
