<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Zend\Form\Form $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'importer');
$this->headLink()->appendStylesheet($this->assetUrl('css/import.css', 'Import'));
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Import'), 1, $translate('Configure reader')); ?>

<div id="primary">
    <h2><?php echo $escape($translate('Configure reader')); ?></h2>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
