<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Form\ImporterDeleteForm $form
 * @var \BulkImport\Api\Representation\ImporterRepresentation $entity
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'importer');
$this->headLink()->appendStylesheet($this->assetUrl('css/import.css', 'Import'));
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Import'), 1, $translate('Delete importer')); ?>

<div id="primary">
    <h2><?php echo $escape(sprintf($translate('Delete importer (%s)'), $entity->getName())); ?></h2>
    <p><?php echo $escape($translate('Are you sure you want to delete this importer ?')); ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
