<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var string $resourceType
 * @var array $formatters
 *
 * @deprecated Use helper bulkExport() and template bulk-export instead.
 */

if (!count($formatters) || !count($resources)):
    return;
endif;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');

$query = $this->params()->fromQuery();
unset($query['page'], $query['per_page']);

if (empty($resourceType) || $resourceType === 'resource'):
    $resourceType = 'resource';
    $query = ['id' => implode(',', array_map(function($v) { return $v->id(); }, $resources))];
endif;

$route = $this->status()->isAdminRequest() ? 'admin/resource-output' : 'site/resource-output';
$this->headLink()->appendStylesheet($assetUrl('css/bulk-export.css', 'BulkExport'));
?>

<div class="bulk-export">
    <h4><?= $translate('Export') ?></h4>
    <ul class="formatters">
    <?php foreach ($formatters as $format => $label): ?>
        <?php $urlFormat = $url($route, ['controller' => $resourceType, 'format' => $format], ['query' => $query], true); ?>
        <li><a download="download" class="download-<?= $format ?>" href="<?= $escapeAttr($urlFormat) ?>"><?= $label ?></a></li>
    <?php endforeach; ?>
    </ul>
</div>
