<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $formatters
 *
 * @deprecated Use helper bulkExport() and template bulk-export instead.
 */

if (!count($formatters)):
    return;
endif;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');

$route = $this->status()->isAdminRequest() ? 'admin/resource-output-id' : 'site/resource-output-id';
$this->headLink()->appendStylesheet($assetUrl('css/bulk-export.css', 'BulkExport'));
?>

<div class="meta-group bulk-export">
    <h4><?= $translate('Export') ?></h4>
    <ul class="formatters value">
    <?php foreach ($formatters as $format => $label): ?>
        <?php $urlFormat = $url($route, ['controller' => $resource->getControllerName(), 'format' => $format, 'id' => $resource->id()], true); ?>
        <li><a download="download" href="<?= $escapeAttr($urlFormat) ?>"><?= $label ?></a></li>
    <?php endforeach; ?>
    </ul>
</div>
