<?php
$this->htmlElement('body')->appendAttribute('class', 'importer');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/import.css', 'Import'));
$form->prepare();
?>

<?php echo $this->pageTitle($this->translate('Import'), 1, $this->translate('Delete importer')); ?>

<div id="primary">
    <h2><?php echo $escape(sprintf($this->translate('Delete importer (%s)'), $entity->getName())); ?></h2>
    <p><?php echo $escape($this->translate('Are you sure you want to delete this importer ?')); ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>