<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExportRepresentation[] $exports
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/bulk-export-admin.css', 'BulkExport'));

$this->htmlElement('body')->appendAttribute('class', 'bulk-exports browse');
?>

<?= $this->pageTitle($translate('Exports'), 1, $translate('Bulk export')) ?>

<div id="bulk-export">
    <h2><?= $escape($translate('Exports')) ?></h2>

    <?php if (count($exports)): ?>
        <?= $this->pagination() ?>
        <?php $this->trigger('view.browse.before'); ?>
        <?= $this->partial('bulk/admin/export/export-table', ['exports' => $exports]) ?>
        <?php $this->trigger('view.browse.after'); ?>
    <?php else: ?>
        <div class="no-resources">
            <p><?= $escape($translate('No exports yet.')) ?></p>
        </div>
    <?php endif; ?>
</div>
