<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExportRepresentation[] $exports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$urlBase = $url('top') . 'files/bulk_export/';
?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $escape($translate('Exporter')); ?></th>
            <th><?php echo $escape($translate('Status')); ?></th>
            <th><?php echo $escape($translate('Started')); ?></th>
            <th><?php echo $escape($translate('Completed')); ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($exports as $export): ?>
            <?php $status = $export->status(); ?>
            <?php $filename = $export->filename(); ?>
            <?php $fileUrl = $export->isCompleted() && $filename ? $urlBase . $filename : ''; ?>
            <tr>
                <td>
                    <?php echo $export->exporter()->label(); ?>
                    <ul class="actions">
                        <?php if ($export->isInProgress()): ?>
                        <li><?php echo $hyperlink('', $url('admin/id', ['controller' => 'job', 'action' => 'stop', 'id' => $export->job()->id()]), [
                            'class' => 'fas fa-times-circle',
                            'title' => $translate('Stop'), // @translate
                        ]); ?></li>
                        <?php endif; ?>
                        <?php if ($fileUrl): ?>
                        <li><?php
                        echo $hyperlink('', $fileUrl, [
                            'class' => 'fas fa-cloud-upload-alt',
                            'title' => $translate('Get file'), // @translate
                        ]); ?></li>
                        <?php endif; ?>
                    </ul>
                </td>
                <td><?php echo $fileUrl ? $hyperlink($status, $fileUrl) : $status; ?></td>
                <td><?php if ($export->started()) echo $export->started()->format('Y-m-d H:i:s'); ?></td>
                <td><?php if ($export->ended()) echo $export->ended()->format('Y-m-d H:i:s'); ?></td>
                <td>
                    <?php echo $this->hyperlink($translate('See logs'), $this->url('admin/bulk-export/id', ['controller' => 'export', 'action' => 'logs', 'id' => $export->id()])); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
