<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExportRepresentation[] $exports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exports show');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-export.css', 'BulkExport'));
?>

<?php echo $this->pageTitle($translate('Exports'), 1, $translate('Bulk export')); ?>

<div id="content">
    <h2><?php echo $escape($translate('Exports')); ?></h2>

    <?php if (count($exports)): ?>
        <?php echo $this->pagination(); ?>
        <?php echo $this->partial('bulk/admin/export/export-table', ['exports' => $exports]); ?>
    <?php else: ?>
        <p><?php echo $escape($translate('No exports yet.')); ?></p>
    <?php endif; ?>
</div>
