<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExportRepresentation[] $exports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exports browse');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-export-admin.css', 'BulkExport'));
?>

<?= $this->pageTitle($translate('Exports'), 1, $translate('Bulk export')) ?>

<div id="content">
    <h2><?= $escape($translate('Exports')) ?></h2>

    <?php if (count($exports)): ?>
        <?= $this->pagination() ?>
        <?= $this->partial('bulk/admin/export/export-table', ['exports' => $exports]) ?>
    <?php else: ?>
        <p><?= $escape($translate('No exports yet.')) ?></p>
    <?php endif; ?>
</div>
