<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExportRepresentation $export
 * @var \Log\Api\Representation\LogRepresentation[] $logs
 * @var int $severity
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$strLength = 240;

$this->htmlElement('body')->appendAttribute('class', 'bulk-exports logs browse');

$script = <<<'JS'
$(document).ready(function() {
    $('select[name=severity]').on('change', function() {
        $(this).closest('form').submit();
    });
});
JS;

$this->headLink()
    ->appendStylesheet($this->assetUrl('css/bulk-export-admin.css', 'BulkExport'))
    ->appendStylesheet($this->assetUrl('vendor/webui-popover/jquery.webui-popover.min.css', 'Log'))
    ->appendStylesheet($this->assetUrl('css/log.css', 'Log'));
$this->headScript()
    ->appendScript($script)
    ->appendFile($this->assetUrl('vendor/webui-popover/jquery.webui-popover.min.js', 'Log'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($this->assetUrl('js/log.js', 'Log'), 'text/javascript', ['defer' => 'defer']);

$severityNames = [
    \Laminas\Log\Logger::EMERG => $escape($translate('Emergency')),
    \Laminas\Log\Logger::ALERT => $escape($translate('Alert')),
    \Laminas\Log\Logger::CRIT => $escape($translate('Critical')),
    \Laminas\Log\Logger::ERR => $escape($translate('Error')),
    \Laminas\Log\Logger::WARN => $escape($translate('Warning')),
    \Laminas\Log\Logger::NOTICE => $escape($translate('Notice')),
    \Laminas\Log\Logger::INFO => $escape($translate('Info')),
    \Laminas\Log\Logger::DEBUG => $escape($translate('Debug')),
];
?>

<?= $this->pageTitle(sprintf($translate('Export #%d'), $export->id()), 1, $translate('Bulk export')) ?>

<div id="page-actions">
    <?php if ($export->isInProgress()): ?>
    <?= $hyperlink($translate('Attempt to stop job'), $url('admin/bulk-export/id', ['controller' => 'export', 'action' => 'stop', 'id' => $export->id()], true), ['class' => 'button']) ?>
    <?php endif; ?>
    <?php if (count($logs)): ?>
    <?= $hyperlink(sprintf($translate('Manage logs')), $url('admin/log/default', [], ['query' => ['reference' => 'bulk/export/' . $export->id()]]), ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\BulkExport')->menu() ?>
</nav>

<div id="bulk-export">
    <form>
        <label>
            <?= $escape($translate('Show only messages whose severity is higher than or equal to')) ?>
            <select name="severity">
                <?php foreach ($severityNames as $i => $name): ?>
                    <?php $selected = ($i === $severity) ? 'selected' : ''; ?>
                    <option value="<?= $i ?>" <?= $selected ?>><?= $name ?></option>
                <?php endforeach; ?>
            </select>
        </label>
    </form>
    <br/>

<?php if (count($logs)): ?>
    <?= $pagination = (string) $this->pagination() ?>

    <table class="tablesaw batch-edit" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <th><?= $escape($translate('Message')) ?></th>
            <th><?= $escape($translate('Severity')) ?></th>
            <th><?= $escape($translate('Time')) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($logs as $log) { ?>
            <tr>
                <td class="webui-popover-parent">
                    <span class="log-message">
                        <?php $shouldEscape = $log->text()->escapeHtml(); ?>
                        <?php $text = $log->text()->translate(); ?>
                        <?php $isLong = mb_strlen($shouldEscape ? $text : strip_tags($text)) > $strLength; ?>
                        <?php if ($isLong): ?>
                        <span class="log-message-truncated truncate"><?= nl2br($escape(mb_substr(strip_tags($text), 0, $strLength))) . '…' ?></span>
                        <?php else: ?>
                        <?= $shouldEscape ? $escape($text) : $text ?>
                        <?php endif; ?>
                    </span>
                    <ul class="actions">
                        <?php if ($isLong): ?>
                        <li><?= $hyperlink('', '#', [
                                'class' => 'o-icon- fa fa-expand popover',
                                'title' => $translate('Full log'),
                            ]) ?>
                            <div class="log-message-full webui-popover-content webui-popover-current"><?= $shouldEscape ? nl2br($escape($text)) : nl2br($text) ?></div>
                        </li>
                        <?php endif; ?>
                    </ul>
                </td>
                <td><?= $translate($log->severityLabel()) ?> </td>
                <td><?= $i18n->dateFormat($log->created(), 'medium', 'medium') ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    <?= $pagination ?>

<?php else: ?>
    <p><?= $escape($translate('No logs yet.')); ?> <a href=""><?= $escape($translate('Refresh page')) ?></a></p>
<?php endif; ?>
</div>
