<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExportRepresentation $export
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$jobState = $plugins->get('jobState');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->headLink()
    ->appendStylesheet($assetUrl('css/job.css', 'Log'))
    ->appendStylesheet($assetUrl('css/bulk-export-admin.css', 'BulkExport'));

$this->headScript()
    ->appendFile($assetUrl('js/job.js', 'Log'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'bulk-exports show');

$job = $export->job();
$state = $jobState($job);

$exporter = $export->exporter();
?>

<?= $this->pageTitle(sprintf($translate('Export #%d'), $export->id()), 1, $translate('Bulk export')) ?>

<div id="page-actions">
    <?php if ($export->isInProgress()): ?>
    <?php if ($state): ?>
    <?= $jobState($job, ['output' => 'html', 'inline' => true]) ?>
    <?php endif; ?>
    <?= $hyperlink($translate('Attempt to stop job'), $url('admin/bulk-export/id', ['controller' => 'export', 'action' => 'stop', 'id' => $export->id()], true), ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\BulkExport')->menu() ?>
</nav>

<div id="bulk-export">
    <h3><?= $translate('Status') ?></h3>
    <ul>
        <li><?= sprintf($translate('Exporter: %s'), $exporter ? $exporter->label() : $translate('Unknown')) ?></li>
        <li><?= sprintf($translate('Owner: %s'), $export->owner() ? $hyperlink($export->owner()->name(), $export->owner()->adminUrl()) : $translate('[Unknown]')) ?></li>
        <li><?= sprintf($translate('Comment: %s'), $export->comment()) ?></li>
        <li><?= sprintf($translate('Status: %s'), $export->statusLabel()) ?></li>
        <?php if ($state): ?>
        <li>
            <span><?= $translate('System state:') ?></span>
            <?= $jobState($job, ['output' => 'html', 'include_state_label' => true, 'inline' => true]) ?>
        </li>
        <?php endif; ?>
        <?php if ($v = $export->started()): ?>
        <li><?= sprintf($translate('Started: %s'), $i18n->dateFormat($v, 'medium', 'medium')) ?></li>
        <?php endif; ?>
        <?php if ($v = $export->ended()): ?>
        <li><?= sprintf($translate('Ended: %s'), $i18n->dateFormat($v, 'medium', 'medium')) ?></li>
        <?php endif; ?>
    </ul>
    <h3><?= $escape($translate('Parameters')) ?></h3>
    <h4><?= $escape($translate('Formatter')) ?></h4>
    <div class="value">
        <pre><?php
            echo $escape(json_encode($export->formatterParams(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));
        ?></pre>
    </div>
</div>
