<?php
use Import\Configurable as ConfigurableImport;

$this->htmlElement('body')->appendAttribute('class', 'importer jobs undo');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/import.css', 'Import'));
?>

<?php echo $this->pageTitle($this->translate('Import'), 1, $this->translate('Imports')); ?>

<div id="primary">
    <h2><?php echo $escape($this->translate('Imports'));?></h2>

    <?php if (!empty($imports)) {?>
        <?php echo $this->pagination(); ?>
        <?php echo $this->partial('import/imports/imports-table', ['imports' => $imports]); ?>
    <?php } else { ?>
        <p><?php echo $escape($this->translate('No imports yet.'));?></p>
    <?php } ?>
</div>
