<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImportRepresentation[] $imports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $escape($translate('Importer')); ?></th>
            <th><?php echo $escape($translate('Status')); ?></th>
            <th><?php echo $escape($translate('Started')); ?></th>
            <th><?php echo $escape($translate('Completed')); ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($imports as $import): ?>
            <tr>
                <td><?php echo $import->importer()->label(); ?></td>
                <td><?php echo $import->status(); ?></td>
                <td><?php if ($import->started()) echo $import->started()->format('Y-m-d H:i:s'); ?></td>
                <td><?php if ($import->ended()) echo $import->ended()->format('Y-m-d H:i:s'); ?></td>
                <td>
                    <?php echo $this->hyperlink($translate('See logs'), $this->url('admin/bulk/id', ['controller' => 'import', 'action' => 'logs', 'id' => $import->id()])); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
