<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImportRepresentation $import
 * @var \BulkImport\Api\Representation\ImportRepresentation $resource
 * @var \Log\Api\Representation\LogRepresentation[] $logs
 * @var int $severity
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-import import');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
$severityNames = [
    \Zend\Log\Logger::EMERG => $escape($translate('Emergency')),
    \Zend\Log\Logger::ALERT => $escape($translate('Alert')),
    \Zend\Log\Logger::CRIT => $escape($translate('Critical')),
    \Zend\Log\Logger::ERR => $escape($translate('Error')),
    \Zend\Log\Logger::WARN => $escape($translate('Warning')),
    \Zend\Log\Logger::NOTICE => $escape($translate('Notice')),
    \Zend\Log\Logger::INFO => $escape($translate('Info')),
    \Zend\Log\Logger::DEBUG => $escape($translate('Debug')),
];
?>

<?php echo $this->pageTitle($translate('Import logs'), 1, $translate('Bulk import')); ?>
<div id="content">
    <h2><?php echo $escape($translate('Import logs')); ?></h2>

    <form>
        <label>
            <?php echo $escape($translate('Show only messages whose severity is higher than or equal to')); ?>
            <select name="severity">
                <?php foreach ($severityNames as $i => $name): ?>
                    <?php $selected = ($i === $severity) ? 'selected' : ''; ?>
                    <option value="<?php echo $i; ?>" <?php echo $selected; ?>><?php echo $name; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <button type="submit"><?php echo $translate('Show'); ?></button>
    </form>

    <?php if (count($logs)): ?>
        <?php echo $this->pagination(); ?>

        <table class="tablesaw" data-tablesaw-mode="stack">
            <thead>
            <tr>
                <th><?php echo $escape($translate('Time')); ?></th>
                <th><?php echo $escape($translate('Message')); ?></th>
                <th><?php echo $escape($translate('Severity')); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($logs as $log) { ?>
                <tr>
                    <td><?php echo $log->created()->format('Y-m-d H:i:s'); ?></td>
                    <td><?php echo $log->message()->translate(); ?></td>
                    <td><?php echo $translate($log->severityLabel()); ?> </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
        <?php echo $this->hyperlink(sprintf($translate('Manage logs')),
            $this->url('admin/log/default', [], ['query' => ['reference' => 'bulk/import/' . $import->id()]])); ?>

    <?php else: ?>
        <p><?php echo $escape($translate('No logs yet.')); ?> <a href=""><?php echo $escape($translate('Refresh page')); ?></a></p>
    <?php endif; ?>
</div>
