<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Interfaces\Reader $reader
 * @var \Zend\Form\Form $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Configure reader'), 1, $translate('Bulk import')); ?>

<div id="content">
    <h2><?php echo $escape($translate('Configure reader')); ?></h2>
    <h3><?php echo $escape(sprintf($translate('Reader: %s'), $reader->getLabel())); ?></h3>
    <p><?php echo $escape($translate('Fill the default values of the reader.')); ?></p>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
