<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Zend\Form\Form $form
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-importers edit');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Configure processor'), 1, $translate('Bulk Import')); ?>

<div id="content">
    <h2><?php echo $escape($translate('Configure processor')); ?></h2>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
