<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\ImporterRepresentation $importer
 * @var \BulkImport\Form\ImporterForm $form
 * @var array $importArgs
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'bulk-import importer');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import.css', 'BulkImport'));
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Start import'), 1, $translate('Bulk import')); ?>

<div id="content">
    <h2><?php echo $escape($translate('Start import')); ?></h2>
    <h3><?php echo $escape($translate('Importer')); ?></h3>
    <p><?php echo $importer->label(); ?></p>
    <?php if (isset($importArgs)): ?>
    <h3><?php echo $escape($translate('Parameters')); ?></h3>
    <div class="value">
        <pre><?php
            echo $escape(json_encode($importArgs, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));
        ?></pre>
    </div>
    <?php endif; ?>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
</div>
