<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Api\Representation\ExporterRepresentation[] $exporters
 * @var \BulkExport\Api\Representation\ExportRepresentation[] $exports
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');

$this->htmlElement('body')->appendAttribute('class', 'bulk-exporters bulk-exports browse');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-export-admin.css', 'BulkExport'));
?>

<?= $this->pageTitle($translate('Bulk export'), 1, $translate('Bulk export')) ?>

<?= $this->partial('bulk/admin/exporter/exporter-table', ['exporters' => $exporters]) ?>

<?php if (!empty($exports)): ?>
    <h2><?= $escape($translate('Last exports')) // @translate?></h2>
    <?= $hyperlink($translate('See all exports'), $this->url('admin/bulk-export/default', ['controller' => 'export', 'action' => 'index'])) ?>
    <?= $this->partial('bulk/admin/export/export-table', ['exports' => $exports]) ?>
<?php endif; ?>
