<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$bulkExport = $plugins->get('bulkExport');
?>

<?= $bulkExport($resource, [
    'heading' => $translate('Export'), // @translate
    'divclass' => 'block resource-block block-bulk-export',
]) ?>
