<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 *
 * @uses \BulkExport\View\Helper\BulkExport::__invoke()
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$bulkExport = $plugins->get('bulkExport');

$this->headScript()
    ->appendFile($this->assetUrl('js/bulk-export.js', 'BulkExport'), 'text/javascript', ['defer' => 'defer']);
?>

<details class="button-details bulk-export-details">
    <summary class="button bulk-export-summary" title="<?= $translate('Export record') ?>" aria-label="<?= $translate('Export record') ?>" aria-expanded="false"><span class="fas fa-cloud-download-alt"></span></summary>
    <?= $bulkExport($resource, [
        'heading' => null,
        'divclass' => 'block resource-block block-bulk-export',
    ]) ?>
</details>
