<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 *
 * @uses \BulkExport\View\Helper\BulkExport::__invoke()
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$bulkExport = $plugins->get('bulkExport');
?>

<?= $bulkExport($resource, [
    'heading' => $translate('Export'), // @translate
]) ?>
