<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 *
 * @uses \BulkExport\View\Helper\BulkExport::__invoke()
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$bulkExport = $plugins->get('bulkExport');
?>

<details class="button-details bulk-export-details">
    <summary class="button"><span class="fas fa-cloud-download-alt"></span></summary>
    <?= $bulkExport($query, [
        'heading' => null,
        'divclass' => 'block resource-block block-bulk-export block-bulk-export-search',
    ]) ?>
</details>
