<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 *
 * @uses \BulkExport\View\Helper\BulkExport::__invoke()
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$bulkExport = $plugins->get('bulkExport');
?>

<?= $bulkExport($query, [
    'heading' => $translate('Export'), // @translate
    'divclass' => 'block resource-block block-bulk-export block-bulk-export-search',
]) ?>
