<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImport\Api\Representation\LogRepresentation[] $logs
 * @var int $severity
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'importer');
$this->headLink()->appendStylesheet($this->assetUrl('css/import.css', 'Import'));
$severityNames = [
    $escape($translate('Emergency')),
    $escape($translate('Alert')),
    $escape($translate('Critical')),
    $escape($translate('Error')),
    $escape($translate('Warning')),
    $escape($translate('Notice')),
    $escape($translate('Info')),
    $escape($translate('Debug')),
];
?>

<?php echo $this->pageTitle($translate('Import'), 1, $translate('Import logs')); ?>
<div id="primary">
    <h2><?php echo $escape($translate('Import logs')); ?></h2>

    <form>
        <label>
            <?php echo $escape($translate('Show only messages whose severity is higher than or equal to')); ?>
            <select name="severity">
                <?php foreach ($severityNames as $i => $name): ?>
                    <?php $selected = ($i === $severity) ? 'selected' : ''; ?>
                    <option value="<?php echo $i; ?>" <?php echo $selected; ?>><?php echo $name; ?></option>
                <?php endforeach; ?>
            </select>
        </label>
        <button type="submit"><?php echo $translate('Show'); ?></button>
    </form>

    <?php if (count($logs)): ?>
        <?php echo $this->pagination(); ?>

        <table class="tablesaw" data-tablesaw-mode="stack">
            <thead>
            <tr>
                <th><?php echo $escape($translate('Time')); ?></th>
                <th><?php echo $escape($translate('Message')); ?></th>
                <th><?php echo $escape($translate('Severity')); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($logs as $log) { ?>
                <tr>
                    <td><?php echo $log->getAdded()->format('Y-m-d H:i:s'); ?></td>
                    <td><?php echo $log->getMessage(); ?></td>
                    <td><?php echo isset($severityNames[$log->getSeverity()]) ? $severityNames[$log->getSeverity()] : $log->getSeverity(); ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

    <?php else: ?>
        <p><?php echo $escape($translate('No logs yet.')); ?> <a href=""><?php echo $escape($translate('Refresh page')); ?></a></p>
    <?php endif; ?>
</div>
