<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \BulkExport\Form\ShaperForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/bulk-export-admin.css', 'BulkExport'));
$this->headScript()
    ->appendFile($assetUrl('js/bulk-export-admin.js', 'BulkExport'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'bulk-shapers edit');

$form->prepare();

$submit = $form->get('form_submit')->get('submit');
$submit->setAttribute('form', $form->getAttribute('id'));
$form->get('form_submit')->remove('submit');
?>

<?= $this->pageTitle($translate('New shaper'), 1, $translate('Bulk Export')) ?>

<div id="bulk-shaper">
    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form) ?>
    <?= $this->form()->closeTag() ?>
</div>

<div id="page-actions">
    <?= $this->formSubmit($submit) ?>
</div>
