<?php
use Import\Interfaces\Configurable as ConfigurableImport;

$this->htmlElement('body')->appendAttribute('class', 'importer jobs undo');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/import.css', 'Import'));
?>

<?php echo $this->pageTitle($this->translate('Import'), 1, $this->translate('Import')); ?>

<h2><?php echo $escape($this->translate('Available importers'));?></h2>
<?php echo $this->hyperlink('Add an importer', $this->url('admin/import/default', ['controller' => 'importers', 'action' => 'add'])); ?>

<?php if(!empty($importers)) { ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <th><?php echo $escape($this->translate('Name'));?></th>
            <th><?php echo $escape($this->translate('Reader'));?></th>
            <th><?php echo $escape($this->translate('Processor'));?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($importers as $importer){ ?>
            <tr>
                <td>
                    <?php echo $this->hyperlink($importer->getName(), $this->url('admin/import/id', ['controller' => 'importers', 'action' => 'start', 'id' => $importer->getId()])); ?>
                </td>
                <td>
                    <?php $reader = $importer->getReader(); ?>
                    <?php echo $reader->getLabel(); ?>
                    <?php if ($reader instanceof ConfigurableImport): ?>
                        (<?php echo $this->hyperlink('Configure', $this->url('admin/import/id', ['controller' => 'importers', 'action' => 'configure-reader', 'id' => $importer->getId()])); ?>)
                    <?php endif; ?>
                </td>
                <td>
                    <?php $processor = $importer->getProcessor(); ?>
                    <?php echo $processor->getLabel(); ?>
                    <?php if ($processor instanceof ConfigurableImport): ?>
                        (<?php echo $this->hyperlink('Configure', $this->url('admin/import/id', ['controller' => 'importers', 'action' => 'configure-processor', 'id' => $importer->getId()])); ?>)
                    <?php endif; ?>
                </td>
                <td>
                <?php echo $this->hyperlink('Edit', $this->url('admin/import/id', ['controller' => 'importers', 'action' => 'edit', 'id' => $importer->getId()])); ?>
                <?php echo $this->hyperlink('Delete', $this->url('admin/import/id', ['controller' => 'importers', 'action' => 'delete', 'id' => $importer->getId()])); ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
<?php } ?>


<?php if (!empty($imports)) {?>
    <h2><?php echo $escape($this->translate('Last imports'));?></h2>
    <?php echo $this->hyperlink('See all imports', $this->url('admin/import/default', ['controller' => 'imports', 'action' => 'index'])); ?>
    <?php echo $this->partial('import/imports/imports-table', ['imports' => $imports]); ?>
<?php } ?>
