<?php
namespace Import\Log;

use Import\Entity\Import as ImportEntity;
use Zend\Log\Logger as ZendLogger;

class Logger extends ZendLogger
{
    protected $import;

    public function setImport(ImportEntity $import)
    {
        $this->import = $import;
    }

    public function log($priority, $message, $extra = [])
    {
        $extra['import'] = $this->import;
        // TODO: Change the autogenerated stub
        return parent::log($priority, $message, $extra);
    }
}
